name: Deploy NestJS to EC2 (Build on EC2)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          # Ensure repo is cloned or updated
          cd ~/pups4sale/nest-backend || mkdir -p ~/pups4sale && cd $_
          if [ ! -d .git ]; then
            git clone https://github.com/munish176081/nest-backend.git .
          else
            git pull origin main
          fi

          # Load NVM
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" || {
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
            source "$HOME/.nvm/nvm.sh"
          }

          # Install Node.js, pnpm, and pm2
          nvm install 20
          npm install -g pnpm pm2

          # Install deps and build
          pnpm install
          pnpm build

          # Restart app using PM2
          pm2 delete backend || true
          pm2 start "pnpm start:prod" --name backend || pm2 restart backend --update-env
