name: Deploy NestJS to EC2 (via build branch)

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-to-ec2
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependencies & Build
      run: |
        pnpm install
        pnpm build

    - name: Commit & Push production build to `build` branch
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -B build
        git add -f dist src package.json pnpm-lock.yaml nest-cli.json
        git commit -m "Deploy: production build - $(date)" || echo "No changes to commit"
        git push --force origin build

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          set -e
          echo "Starting EC2 deployment..."

          # Install Node, pnpm, and pm2 if missing
          if ! command -v node &> /dev/null; then
            echo "Installing Node.js and pnpm..."
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm install 20
            npm install -g pnpm pm2
          fi

          # Load nvm
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          # Go to or create the app directory
          cd ~/pups4sale/nest-backend || mkdir -p ~/pups4sale/nest-backend && cd $_

          # Clone or pull the build branch
          if [ ! -d .git ]; then
            git init
            git remote add origin https://github.com/munish176081/nest-backend.git
            git fetch origin build
            git checkout -t origin/build
          else
            git fetch origin build
            git checkout build
            git pull origin build --rebase
          fi

          echo "Installing production dependencies..."
          pnpm install --prod

          echo "Stopping previous PM2 process..."
          pm2 delete backend || true

          echo "Starting application with PM2..."
          pm2 start "pnpm start:prod" --name backend || pm2 restart backend --update-env

          echo "Deployment complete. PM2 Status:"
          pm2 status
          echo "PM2 Logs (last 10 lines):"
          pm2 logs backend --lines 10
